name: Failure Test
on:
  workflow_dispatch:
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Failure Test
  #       run: exit 1
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Failure Test
        run: echo ${{ github.workflow }}
  call-failed-workflow:
    uses: ./.github/workflows/reusable-workflow.yaml
