name: Failure Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Failure Test
        id: failure
        continue-on-error: true
        run: exit 1
      - run: |
          echo "Rerun"
          echo "${{ steps.failure.outputs.conclusion }}"
