name: Try Self Rerun
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate GitHub Apps token
        id: generate-github-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      # 失敗するテストを実行
      - name: Failure Test
        id: failure
        continue-on-error: true
        run: exit 1
      - run: |
          echo "Rerun"
          echo ${{ steps.failure.outcome }}
          echo ${{ github.run_attempt }}
          echo ${{ github.run_id}}
      # 失敗したら3回までリトライ（上手くいかない）
      - name: rerun-workflow
        if: ${{ steps.failure.outcome == 'failure' && github.run_attempt < 3 }}
        env:
          GH_TOKEN: ${{ steps.generate-github-app-token.outputs.token }}
        run: gh run rerun ${{ github.run_id }} --failed
